const COLORS = {

	BACKGROUND: '#343B63',
	WHITE: '#FFFFFF',
	SKY_BLUE_BUTTON_BACKGROUND: '#00D8FF',
	TRANSPARENT_BLACK_BUTTON_BACKGROUND: 'rgba(255,255,255,0.1)',
	WHITE_INACTIVE: 'rgba(255,255,255,0.3)',
	FORGOT_TEXT_COLOR: '#00D8FF',

	TEXT_INPUT_LABEL_COLOR: '#C2C6CE',
	TRANSPARENT: 'transparent',
	BLACK: '#000000',
	TRANSLUCENT_BLACK: 'rgba(0,0,0,0.17)',
	TRANSLUCENT_BLACK_DARK: 'rgba(0,0,0,0.30)',
	TRANSLUCENT_BLACK_TEXT_SHADOW: 'rgba(0,0,0,0.75)',
	SIGN_UP_SUB_TITLE_COLOR: '#555555',
	BOTTOM_NEXT_BUTTON_VIEW_BACKGROUND_COLOR: '#E8E8E8',
	NEXT_TEXT_COLOR: '#737373',
	BOTTOM_NEXT_BUTTON_SELECTED_VIEW: '#006CEB',
	TRANSLUCENT_BLUE: 'rgba(0,108,235,0.3)',
	GET_INSPIRED_SELECT_BORDER_COLOR: '#3C7ADB',
	GET_INSPIRED_SELECTED_COLOR: '#006CEB',
	NEW_DREAM_LABEL_TEXT_COLOR: '#9B9B9B',
	SEARCH_TEXT_INPUT_BORDER_COLOR: '#D5DDE0',
	LINK_DREAM_MORE_TEXT_COLOR: '#29DEFF',
	LINK_DREAM_TEXT_INPUT_BORDER_COLOR: 'rgba(0,0,0,0.1)',
	LINK_DREAM_TEXT_INPUT_COLOR: 'rgba(0,0,0,0.4)',
	SWITCH_COLOR: 'rgba(0,0,0,0.2)',
	SWITCH_COLOR_ACTIVE: '#3C7ADB',
	LOCATION_DESCRIPTION: '#1faadb',
	FOLLOW_TEXT_COLOR: '#3C7ADB',
	COMMENT_TEXT_COLOR: '#747374',
	COMMENT_VIEW_COLOR: '#F0F3F4',
	GRAY: '#DEDEDE',
	GRAY_COLOR: 'gray',
	RADIO_BUTTON_COLOR: '#2db397',
	DRAWER_BACKGROUND_COLOR: '#252861',

	//23 Nov
	//progress bar color
	PROGRESS1: '#FFFFFF',
	PROGRESS2: '#FFFFFF',
	PROGRESS3: '#FFFFFF',
	//


	LIGHT_GRAY_TEXT_COLOR: '#A1A3B9',

	//24 Nov
	PROPERTY_TITLE_COLOR: '#162441',
	PROPERTY_SUB_TITLE_COLOR: '#7F829F',
	NOTICE_BOARD_TEXT_TITLE_COLOR: '#00D8FF',
	NOTICE_BOARD_TEXT_TITLE_COLOR: '#00D8FF',


	//28 Nov
	UPLOAD_IMAGE_BUTTON_COLOR: '#F27815',



	//vishu

	ADD_PROPERTY_INPUT_VIEW_COLOR: '#DBDDEE',
	ADD_PROPERT_LABEL_TEXT_COLOR: '#162441',
	ADD_PROPERT_TITLE_TEXT_COLOR: '#121A32',
	ADD_PROPERTY_DOT_COLOR: '#E2E4ED',
	DROP_DOWN_BACKGROUND_COLOR: '#EBECF2',

	FILTER_TEXT_VIEW_COLOR: '#7F829F',
	REFINE_RESULT_TEXT_COLOR: '#3991EE',

	STATUS_GREEN_COLOR: '#47BD45',
	STATUS_YELLOW_COLOR: '#F4C323',
	STAUS_RED_COLOR: '#FF5757',
	TAG_VIEW_COLOR: 'rgba(70,164,242,0.22)',
	TAG_VIEW_TEXT_COLOR: '#46A4F2',
	DATE_COLOR: '#FBBC13',

	//Maintenance status 
	MAINTENANCE_COMPLETED_STATUS: '#4CBB4C',
	MAINTENANCE_ACCEPTED_STATUS: '#FDC614',
	MAINTENANCE_SENT_STATUS: '#37BBD2',
	MAINTENANCE_OVER_DUE_STATUS: '#FF5757',
	MAINTENANCE_BOOKED_STATUS: '#A45CD5',
	MAINTENANCE_CATEGORY_COLOR: '#7F829E',

	//Edit profile
	EDIT_PROFILE_BACKGROUND_COLOR: '#22255C',
	STAR_COLOR: '#FAC818',
	EMPTY_STAR_COLOR: '#CFD2DB',

	//Home screen thread
	ACTIVE_THREAD_TEXT_COLOR: '#AC6A39',

	SELECTED_USER_LIST_ITEM_COLOR: '#BFF5FF',

	TEXT_COLOR_SKY_BLUE: '#1ACFFF',

	//New maintenance request 
	PICK_FROM_SAVED_TRADERS: '#1ACFFF',

	SETTING_SCREEN_BG_COLOR: '#F8F9FE',

	LEASE_RZENUAL_TEXT_COLOR: '#FC3D46',

	APPROVE_GRAY_TEXT_COLOR: '#B2B5C3',
	LISTING_BG_COLOR: '#D5D8DC',
	RATING_TEXT_COLOR: '#2CB499',

	//Chat BG color
	RECEIVER_BG_COLOR:'#F0F2FC',
	SENDER_BG_COLOR:'#46A4F2',
	



}
export default COLORS;
